name: Build, release & push to website

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    name: Build PDF & update release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout CV repo
        uses: actions/checkout@v4

      - name: Compile PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Generate front page preview
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          pdftoppm -jpeg -f 1 -l 1 cv.pdf cv
        shell: bash

      - name: Update latest release with new PDF & preview
        uses: IsaacShelton/update-existing-release@v1.3.3
        with:
          token: ${{ github.token }}
          release: "Latest CV PDF"
          tag: "latest"
          replace: true
          files: >
            cv.pdf
            cv-1.jpg
          body: "This release contains the latest compiled version of my CV as a PDF file"

      - name: Archive compiled PDF for next job
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: cv.pdf

  push-to-website:
    name: Push PDF to website
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: dariotrinchero/dariotrinchero.github.io
          ref: master
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Retrieve archived PDF
        uses: actions/download-artifact@v4
        with:
          name: cv-pdf

      - name: Commit new PDF
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "dariotrinchero@users.noreply.github.com"
          mv cv.pdf files/
          git add files
          git commit -m "Update CV." || echo "No modifications"
          git push origin master
